name: 'orca_dbt_transformation'
version: '0.1.0'
config-version: 2
profile: 'orca'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
        
models:
  orca_dbt_transformation:
    +database: orca
    +persist_docs:
      relation: true
      columns: false # currently not supported for views in duckdb/ducklake
    marts:
      +materialized: view
      +schema: marts
      +group: marts
