name: 'orca_transform'
version: '0.1.0'
config-version: 2
profile: 'orca'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
        
models:
  orca_transform:
    b_staging:
      +materialized: view
      +schema: b_staging
    c_marts:
      +materialized: table
      +schema: c_marts
